--
-- TYPE_INFO_SEQ  (Sequence) 
--
CREATE SEQUENCE TYPE_INFO_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

--
-- OBJECT_INFO_SEQ  (Sequence) 
--
CREATE SEQUENCE OBJECT_INFO_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- DATA_VALUE_SEQ  (Sequence) 
--
CREATE SEQUENCE DATA_VALUE_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- DATA_INFO_SEQ  (Sequence) 
--
CREATE SEQUENCE DATA_INFO_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

--
-- TYPE_INFO  (Table) 
--
CREATE TABLE TYPE_INFO
(
  ID           NUMBER(3)                        NOT NULL,
  NAME         VARCHAR2(64 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(200 BYTE)
)

PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- DATA_INFO  (Table) 
--
CREATE TABLE DATA_INFO
(
  ID            NUMBER(5)                       NOT NULL,
  NAME          VARCHAR2(64 BYTE)               NOT NULL,
  DESCRIPTION   VARCHAR2(200 BYTE),
  TYPE_INFO_ID  NUMBER(3)                       NOT NULL
)

PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- OBJECT_INFO  (Table) 
--
CREATE TABLE OBJECT_INFO
(
  ID            NUMBER(5)                       NOT NULL,
  TYPE_INFO_ID  NUMBER(3)                       NOT NULL,
  NAME          VARCHAR2(64 BYTE)               NOT NULL,
  DESCRIPTION   VARCHAR2(200 BYTE)
)

PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

--
-- DATA_VALUE  (Table) 
--
CREATE TABLE DATA_VALUE
(
  ID              NUMBER(10)                    NOT NULL,
  DATA_INFO_ID    NUMBER(5)                     NOT NULL,
  OBJECT_INFO_ID  NUMBER(5)                     NOT NULL,
  VALUE_TIME      TIMESTAMP(6)                  NOT NULL,
  VALUE           NUMBER                        NOT NULL
)

PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

--
-- TYPE_INFO_PK  (Index) 
--
CREATE UNIQUE INDEX TYPE_INFO_PK ON TYPE_INFO
(ID)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- TYPE_INFO_UN_NAME  (Index) 
--
CREATE UNIQUE INDEX TYPE_INFO_UN_NAME ON TYPE_INFO
(NAME)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- DATA_INFO_PK  (Index) 
--
CREATE UNIQUE INDEX DATA_INFO_PK ON DATA_INFO
(ID)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- DATA_INFO_UN_TYPE_INFO_NAME  (Index) 
--
CREATE UNIQUE INDEX DATA_INFO_UN_TYPE_INFO_NAME ON DATA_INFO
(TYPE_INFO_ID, NAME)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- OBJECT_INFO_PK  (Index) 
--
CREATE UNIQUE INDEX OBJECT_INFO_PK ON OBJECT_INFO
(ID)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- OBJECT_INFO_UN_TYPE_INFO_NAME  (Index) 
--
CREATE UNIQUE INDEX OBJECT_INFO_UN_TYPE_INFO_NAME ON OBJECT_INFO
(TYPE_INFO_ID, NAME)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- DATA_VALUE_PK  (Index) 
--
CREATE UNIQUE INDEX DATA_VALUE_PK ON DATA_VALUE
(ID)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- DATA_VALUE_UN_DI_OI_VT  (Index) 
--
CREATE UNIQUE INDEX DATA_VALUE_UN_DI_OI_VT ON DATA_VALUE
(DATA_INFO_ID, OBJECT_INFO_ID, VALUE_TIME)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- TYPE_INFO_BI  (Trigger) 
--
CREATE OR REPLACE TRIGGER TYPE_INFO_BI 
  before insert on Type_Info              
  for each row
begin  
  if :new.ID is null then
    select Type_Info_Seq.NextVal into :new.ID from dual;
  end if;
end;
/

--
-- OBJECT_INFO_BI  (Trigger) 
--
CREATE OR REPLACE TRIGGER OBJECT_INFO_BI
  before insert on OBJECT_INFO            
  for each row
begin  
  if :new.ID is null then
    select Object_Info_Seq.NextVal into :new.ID from dual;
  end if;
end;
/

--
-- DATA_VALUE_BI  (Trigger) 
--
CREATE OR REPLACE TRIGGER DATA_VALUE_BI 
  before insert on DATA_VALUE              
  for each row
begin  
  if :new.ID is null then
    select Data_Value_Seq.NextVal into :new.ID from dual;
  end if;
end;
/

--
-- DATA_INFO_BI  (Trigger) 
--
CREATE OR REPLACE TRIGGER DATA_INFO_BI
  before insert on DATA_INFO              
  for each row
begin  
  if :new.ID is null then
    select Data_Info_Seq.NextVal into :new.ID from dual;
  end if;
end;
/

-- 
-- Non Foreign Key Constraints for Table TYPE_INFO 
-- 
ALTER TABLE TYPE_INFO ADD (
  CONSTRAINT TYPE_INFO_PK
  PRIMARY KEY
  (ID)
  USING INDEX TYPE_INFO_PK
  ENABLE VALIDATE);

ALTER TABLE TYPE_INFO ADD (
  CONSTRAINT TYPE_INFO_UN_NAME
  UNIQUE (NAME)
  USING INDEX TYPE_INFO_UN_NAME
  ENABLE VALIDATE);

-- 
-- Non Foreign Key Constraints for Table DATA_INFO 
-- 
ALTER TABLE DATA_INFO ADD (
  CONSTRAINT DATA_INFO_PK
  PRIMARY KEY
  (ID)
  USING INDEX DATA_INFO_PK
  ENABLE VALIDATE);

ALTER TABLE DATA_INFO ADD (
  CONSTRAINT DATA_INFO_UN_TYPE_INFO_NAME
  UNIQUE (TYPE_INFO_ID, NAME)
  USING INDEX DATA_INFO_UN_TYPE_INFO_NAME
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table OBJECT_INFO 
-- 
ALTER TABLE OBJECT_INFO ADD (
  CONSTRAINT OBJECT_INFO_PK
  PRIMARY KEY
  (ID)
  USING INDEX OBJECT_INFO_PK
  ENABLE VALIDATE);

ALTER TABLE OBJECT_INFO ADD (
  CONSTRAINT OBJECT_INFO_UN_TYPE_INFO_NAME
  UNIQUE (TYPE_INFO_ID, NAME)
  USING INDEX OBJECT_INFO_UN_TYPE_INFO_NAME
  ENABLE VALIDATE);

-- 
-- Non Foreign Key Constraints for Table DATA_VALUE 
-- 
ALTER TABLE DATA_VALUE ADD (
  CONSTRAINT DATA_VALUE_PK
  PRIMARY KEY
  (ID)
  USING INDEX DATA_VALUE_PK
  ENABLE VALIDATE);

ALTER TABLE DATA_VALUE ADD (
  CONSTRAINT DATA_VALUE_UN_DI_OI_VT
  UNIQUE (DATA_INFO_ID, OBJECT_INFO_ID, VALUE_TIME)
  USING INDEX DATA_VALUE_UN_DI_OI_VT
  ENABLE VALIDATE);

-- 
-- Foreign Key Constraints for Table DATA_INFO 
-- 
ALTER TABLE DATA_INFO ADD (
  CONSTRAINT DATA_INFO_FK_TYPE_INFO 
  FOREIGN KEY (TYPE_INFO_ID) 
  REFERENCES TYPE_INFO (ID)
  ENABLE VALIDATE);

-- 
-- Foreign Key Constraints for Table OBJECT_INFO 
-- 
ALTER TABLE OBJECT_INFO ADD (
  CONSTRAINT OBJECT_INFO_FK_TYPE_INFO 
  FOREIGN KEY (TYPE_INFO_ID) 
  REFERENCES TYPE_INFO (ID)
  ENABLE VALIDATE);

-- 
-- Foreign Key Constraints for Table DATA_VALUE 
-- 
ALTER TABLE DATA_VALUE ADD (
  CONSTRAINT DATA_VALUE_FK_DATA_INFO 
  FOREIGN KEY (DATA_INFO_ID) 
  REFERENCES DATA_INFO (ID)
  ENABLE VALIDATE);

ALTER TABLE DATA_VALUE ADD (
  CONSTRAINT DATA_VALUE_FK_OBJECT_INFO 
  FOREIGN KEY (OBJECT_INFO_ID) 
  REFERENCES OBJECT_INFO (ID)
  ENABLE VALIDATE);
  
CREATE TABLE  "FINISHED_PRODUCT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MELT_ID" NUMBER NOT NULL ENABLE, 
	"FURNACE_NUMBER" NUMBER NOT NULL ENABLE, 
	"MELT_NUMBER" NUMBER NOT NULL ENABLE, 
	"STACK_NUMBER" NUMBER NOT NULL ENABLE, 
	"WEIGHT" NUMBER NOT NULL ENABLE, 
	"RECEIPT_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "FINISHED_PRODUCT_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER  "BI_FINISHED_PRODUCT" 
  before insert on "FINISHED_PRODUCT"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "FINISHED_PRODUCT_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_FINISHED_PRODUCT" ENABLE;