//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alvasoft.ODTIntegration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class OracleCommands : global::System.Configuration.ApplicationSettingsBase {
        
        private static OracleCommands defaultInstance = ((OracleCommands)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OracleCommands())));
        
        public static OracleCommands Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DATA_EXCHANGE.GET_MPU")]
        public string GettingCastPlan {
            get {
                return ((string)(this["GettingCastPlan"]));
            }
            set {
                this["GettingCastPlan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("o_cursor")]
        public string GettingCastPlan_p1 {
            get {
                return ((string)(this["GettingCastPlan_p1"]));
            }
            set {
                this["GettingCastPlan_p1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i_furnace_number")]
        public string GettingCastPlan_p2 {
            get {
                return ((string)(this["GettingCastPlan_p2"]));
            }
            set {
                this["GettingCastPlan_p2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into FINISHED_PRODUCT(melt_id, furnace_number, melt_number, stack_number, " +
            "weight, receipt_time) values(:melt_id, :furnace_number, :melt_number, :stack_num" +
            "ber, :weight, :receipt_time)")]
        public string InsertFinishedProduct {
            get {
                return ((string)(this["InsertFinishedProduct"]));
            }
            set {
                this["InsertFinishedProduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("melt_id")]
        public string pMeltId {
            get {
                return ((string)(this["pMeltId"]));
            }
            set {
                this["pMeltId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("furnace_number")]
        public string pFurnaceNumber {
            get {
                return ((string)(this["pFurnaceNumber"]));
            }
            set {
                this["pFurnaceNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("melt_number")]
        public string pMeltNumber {
            get {
                return ((string)(this["pMeltNumber"]));
            }
            set {
                this["pMeltNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stack_number")]
        public string pStackNumber {
            get {
                return ((string)(this["pStackNumber"]));
            }
            set {
                this["pStackNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("weight")]
        public string pWeight {
            get {
                return ((string)(this["pWeight"]));
            }
            set {
                this["pWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receipt_time")]
        public string pReceiptTime {
            get {
                return ((string)(this["pReceiptTime"]));
            }
            set {
                this["pReceiptTime"] = value;
            }
        }
    }
}
