//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alvasoft.ODTIntegration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class OracleCommands : global::System.Configuration.ApplicationSettingsBase {
        
        private static OracleCommands defaultInstance = ((OracleCommands)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OracleCommands())));
        
        public static OracleCommands Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DATA_EXCHANGE.GET_MPU")]
        public string GetCastPlanProcedure {
            get {
                return ((string)(this["GetCastPlanProcedure"]));
            }
            set {
                this["GetCastPlanProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("o_cursor")]
        public string aCursor {
            get {
                return ((string)(this["aCursor"]));
            }
            set {
                this["aCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i_furnace_number")]
        public string aFurnaceNumber {
            get {
                return ((string)(this["aFurnaceNumber"]));
            }
            set {
                this["aFurnaceNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into FINISHED_PRODUCT(melt_id, furnace_number, melt_number, stack_number, " +
            "weight, receipt_time) values(:melt_id, :furnace_number, :melt_number, :stack_num" +
            "ber, :weight, :receipt_time)")]
        public string InsertFinishedProductCommand {
            get {
                return ((string)(this["InsertFinishedProductCommand"]));
            }
            set {
                this["InsertFinishedProductCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("melt_id")]
        public string pMeltId {
            get {
                return ((string)(this["pMeltId"]));
            }
            set {
                this["pMeltId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("furnace_number")]
        public string pFurnaceNumber {
            get {
                return ((string)(this["pFurnaceNumber"]));
            }
            set {
                this["pFurnaceNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("melt_number")]
        public string pMeltNumber {
            get {
                return ((string)(this["pMeltNumber"]));
            }
            set {
                this["pMeltNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stack_number")]
        public string pStackNumber {
            get {
                return ((string)(this["pStackNumber"]));
            }
            set {
                this["pStackNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("weight")]
        public string pWeight {
            get {
                return ((string)(this["pWeight"]));
            }
            set {
                this["pWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receipt_time")]
        public string pReceiptTime {
            get {
                return ((string)(this["pReceiptTime"]));
            }
            set {
                this["pReceiptTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select t.ID, o.ID, d.ID from TYPE_INFO t, OBJECT_INFO o, DATA_INFO d where (d.TYP" +
            "E_INFO_ID = t.ID) and (o.TYPE_INFO_ID = t.ID) and (t.NAME = :type_name) and (o.N" +
            "AME = :object_name) and (d.NAME = :data_name)")]
        public string GetIdentifiersCommand {
            get {
                return ((string)(this["GetIdentifiersCommand"]));
            }
            set {
                this["GetIdentifiersCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("type_name")]
        public string pTypeName {
            get {
                return ((string)(this["pTypeName"]));
            }
            set {
                this["pTypeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("object_name")]
        public string pObjectName {
            get {
                return ((string)(this["pObjectName"]));
            }
            set {
                this["pObjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data_name")]
        public string pDataName {
            get {
                return ((string)(this["pDataName"]));
            }
            set {
                this["pDataName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into DATA_VALUE(data_info_id, object_info_id, value_time, value) values(:d" +
            "ata_info_id, :object_info_id, :value_time, :value)")]
        public string InsertCurrentValueCommand {
            get {
                return ((string)(this["InsertCurrentValueCommand"]));
            }
            set {
                this["InsertCurrentValueCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data_info_id")]
        public string pDataInfoId {
            get {
                return ((string)(this["pDataInfoId"]));
            }
            set {
                this["pDataInfoId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("object_info_id")]
        public string pObjectInfoId {
            get {
                return ((string)(this["pObjectInfoId"]));
            }
            set {
                this["pObjectInfoId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("value_time")]
        public string pValueTime {
            get {
                return ((string)(this["pValueTime"]));
            }
            set {
                this["pValueTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("value")]
        public string pValue {
            get {
                return ((string)(this["pValue"]));
            }
            set {
                this["pValue"] = value;
            }
        }
    }
}
